### ISSUE TITLE
specification: presolved flag

### ISSUE THREAD

**Issue by mlindauer** [berndbischl/coseal-algsel-benchmark-repo#10]
The format should provide the possibility to select subsets of feature, for instance, by using only certain feature groups (or feature processing steps), right?
However, the presolving flag ({true,false}) at the end of feature_runstatus.arff provides only information about the entire feature computation process.
If I use a feature subset, the presolving flag is maybe incorrect.  

Solution proposal:
a) A flag for presolving for each feature, saying that "if you try to computed this feature, the instance will be solved".
or 
b) We allow as a runstatus for features "presolved", which has the same meaning as describted in a). Therefore, we could remove the presolving flag and define: An instance was presolved if at least one feature has "presolved" as runstatus.

**Comment by kerschke** [comment]
Am I wrong, or did we already integrate solution b) into the specification?

**Comment by mlindauer** [comment]
not exactly.
We still have the last column "presolved" in the spec. We should remove it since it does not give the desired information in all cases.

**Comment by berndbischl** [comment]
Marius, I this OK now from your perspective?

**Comment by mlindauer** [comment]
yes, it's ok in the specification but all data sets have to be changed accordingly.

**Comment by berndbischl** [comment]
Pascal, can you do that? Or coordinate with Cedric?

**Comment by kerschke** [comment]
Not before wednesday... If that's early enough, I can do it.

**Comment by berndbischl** [comment]
No problem.

**Comment by kerschke** [comment]
I don't see any inconsistency within the data sets compared to the specs-file, but I might be misunderstanding you guys. Here's what I thought you're talking about:
1) We're looking at the feature_runstatus.arff
2) The last column of that file is called presolved and is either TRUE or FALSE.
3) It is TRUE, if any of the runstatus-elements of that instance, i.e. any of the previous columns within the same row, contains the wort "presolved".

If that's what you wanted, all the data sets are already up-to-date. Otherwise, please clarify your concerns!

**Comment by mlindauer** [comment]
I removed the column "presolved" in the specification.

**Comment by kerschke** [comment]
Ok, now I see it. For some reason my the specification still looked the same after updating. However, I found it and will update the data accordingly :-)

**Comment by kerschke** [comment]
"presolved"-columns are removed from all "feature_runstatus.arff"-files.
