### ISSUE TITLE
change data sets to new specification version

### ISSUE THREAD

**Issue by mlindauer** [berndbischl/coseal-algsel-benchmark-repo#29]
minimal todos:
- replace feature group definition by feature step definition in description.txt (trivial if only one feature group was defined)
- remove "total" column in feature_cost.arff
- feature_runstatus.arff is now talking about feature steps and not about individual features

**Comment by berndbischl** [comment]
Pascal, can you do this pls?

**Comment by kerschke** [comment]
Ok. But could you please clarify points 1 and 3?! What exactly do you mean be feature steps?

**Comment by mlindauer** [comment]
The idea is: several (or only one) processing steps are maybe necessary (with associated costs) to compute a feature. To model these dependencies between these steps and features (n-to-n relationship), we removed the feature groups and replaced it by feature (processing) steps. 

For further details, please have a look at the specification pdf.

**Comment by kerschke** [comment]
Alright, I see that my question was not very distinct. I get the idea of feature steps, however, I am still not certain w.r.t. some aspects (even after looking at the specs).

Do I have to list a feature into all feature steps that are needed in order to derive that feature (group). Lets say I have a feature that depends on an initial setup (which could e.g. already be used in step 1) and then it does an additional calculation step (step 2), will it be listed in both steps or just in the second one?

In the latter case, I won’t be able to change all the data sets as I don’t know which feature group depends on which steps for all the data sets. Actually, I only know that for my data set (the bbob set). 

Also, I am not sure whether it is my fault or the part in the specs file is not clear enough - but maybe we should make that part more clear.

**Comment by mlindauer** [comment]
If a feature needs both steps to be available,
it has to be listed in both steps.

However, that is not the problem here.
Except your bbob set and the sat sets,
all other sets have only one feature group. Therefore, the changes should be trivial, right?
I have already changed the sat sets; so nothing to do there.

Cheers,
Marius

**Comment by kerschke** [comment]
Great! Than I'll do the rest :-)

**Comment by kerschke** [comment]
Ok, I've changed the data sets. However, I noticed that some data sets (csp, qbf, premarshalling) have no feature_costs.arff. Are those files missing on purpose?

**Comment by mlindauer** [comment]
The readme files says that there is no information about feature costs in these three sets.
So, it seems to be on purpose.

**Comment by kerschke** [comment]
Ok
